### ISSUE TITLE
Dark transparent overlay with blue button on top of native ads

### ISSUE THREAD

**Issue by kubbing** [googleads/googleads-mobile-ios-examples#302] opened 2022-12-07 10:48 UTC
Hi, around November 18th we started experiencing grey overlay with blue CTA button on many native ads. In-feed and fullscreen ads. Happens on all ad units except our house ads. 

The tap action (on any registered subview) triggers this grey overlay that goes away after couple seconds. Ad click is registered only after user taps the blue CTA itself. We do not see anything in the logs.

Out native ads are `UICollectionViewCell` with `GADNativeAdView` subclasses. All subviews are properly registered (headline, body, icon, cta, mediaView). Ad layout validator shows no issues. The gray view's class is `GADoverlayView`.

We did not ship Google-Mobile-Ads-SDK update around November 18th. All recent builds (back to August builds) show are affected.

Any idea what could be causing this?

Stack:
- Xcode 14.1
- Google-Mobile-Ads-SDK (9.13.0)
- GoogleMobileAds-HyBid-Adapters (2.16.1.0)
- GoogleMobileAdsMediationAppLovin (11.5.5.0)
- GoogleMobileAdsMediationFyber (8.1.7.0)
- GoogleMobileAdsMediationInMobi (10.1.1.0)
- MintegralAdSDKAdapterForAdmob (7.1.9.0)
- NimbusSDK/NimbusGAMKit (2.0.0)
- YandexMobileAdsAdMobAdapters (5.2.0.0)

<img width="320" alt="fullscreen" src="https://user-images.githubusercontent.com/324165/206156424-f4a6482a-6cbd-4cd7-8d10-138f1e7cdfa7.jpeg">
<img width="320" alt="in-feed" src="https://user-images.githubusercontent.com/324165/206156782-40bfb086-4c43-4b92-b442-2ac2bdf2a5a3.png">

**Comment by lucasromanomr** [comment] 2023-05-12 19:37
I have a very similar problem, specifically with App installation ads. But it only happens when opening an appstore internally in the app. When you tap on top, an overlay appears in the same way, except that in my case I can't have any kind of action on top.

And also a log appears that the url you tried to run by tapping the button is not a valid url

**Comment by ericleich** [comment] 2023-06-23 19:46
This looks like your app is getting the confirmed click behavior - https://support.google.com/admob/answer/10094971. Closing as this is more of a product question than an issue with the samples itself.

**Closed by ericleich** 2023-06-23 19:46 UTC
