### ISSUE TITLE
rewardVideo problem

### ISSUE THREAD

**Issue by Superdaren** [googleads/googleads-mobile-ios-examples#48] opened 2017-05-14 09:18 UTC
Why do I use this unitID: ca-app-pub-3940256099942544/1712485313 does not have any data that can provide a data test unitID?

**Comment by ericleich** [comment] 2017-05-15 16:22
I don't understand the question. Are you saying that when using `ca-app-pub-3940256099942544/1712485313` you're not getting a rewarded video ad back?

**Comment by Superdaren** [comment] 2017-05-22 06:31
Yes, when I use the test unitID:ca-app-pub-3940256099942544/1712485313 when there is no video advertising data, I use the official unitID when there is advertising video data, if the frequent use of the official id will be title, so I can only use the test ID to test my app , How did not provide the test unitID of the data

**Comment by ericleich** [comment] 2017-05-22 16:55
It sounds like you're saying:

1. The official ad unit ID `ca-app-pub-3940256099942544/1712485313` serves ads
2. Your ad unit ID doesn't serve ads

What is the ad unit ID from your account that you're trying to use to serve ads? Perhaps it isn't configured correctly.

**Comment by azurebld** [comment] 2017-05-27 08:58
i think he means the opposite, because i met this problem too
1. real id is ok, but he's afraid that using real id violate G's policy
2. test id doesnt serve ads, got the following warning : "<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target."

besides, can anyone tell me when does Admob starting to serve its own rewarded video ads? as far as i remember, Admob only had reward ads from 3rd party last year. but this repository has example since March last year. made me quite confused.

from this page: [https://support.google.com/admob/answer/6373180?hl=en](url)
"Rewarded ads are only available from third-party networks that you've selected for mediation"

**Comment by ericleich** [comment] 2017-05-30 15:51
AdMob started to serve its own rewarded video ads in March 2017. Prior to that, the example in this repo asked you to insert your own ad unit ID and you also would have had to include additional libraries into the project for 3p ad networks that you wanted to mediate. Now that AdMob serves its own ads, we added an ad unit ID to the sample to serve rewarded ads (`ca-app-pub-3940256099942544/1712485313`), and the sample works of the box.

The error `Cannot find an ad network adapter with the name(s): com.google.DummyAdapter.` really just means no fill. This ad unit ID above is configured to always serve an AdMob house ad. There are 2 ads pointed at it at the moment, 1 for the [Google Search](https://itunes.apple.com/us/app/google-search-made-just-for-mobile/id284815942?mt=8) app, and 1 for [Bingo Blast](https://itunes.apple.com/us/app/bingo-blast/id594223187?mt=8) was added last week. There isn't any targeting set up against that ad unit, so they should be serving anywhere. I just checked and it's working on my end, so it's not a network-wide house ad serving issue. Only reason I can think of that it wouldn't serve is if you have both of these apps installed already, but that's a long shot.

**Comment by azurebld** [comment] 2017-05-31 00:43
no i dont have these apps.
And i dont use admob to mediate any 3p network, maybe thats the reason?
whatever, i am not going to test that...

**Comment by ericleich** [comment] 2017-06-01 17:42
Nope, you're setting up 3p networks wouldn't make the difference.

Only other way I know to proceed is to figure out what the ad request url looks like from your side, and then we can replay that to see what's different from your test vs. mine. Two ways to get the ad request URL:

1. From terminal, run `adb shell "setprop log.tag.Ads VERBOSE; logcat Ads:* *:S"` prior to loading ads. This should turn on some more verbose logging, which includes the ad request URL that gets sent out.
2. Install and configure [Charles Proxy](https://www.charlesproxy.com/) to inspect your web traffic, make an ad request, and saves the Charles proxy log and share that. This step is more involved if you don't already use Charles Proxy, so I'd recommend trying (1) first.

**Comment by azurebld** [comment] 2017-06-04 10:12
err...

1. adb is for android, right?
2. i checked the website, that software is for win/linux/mac, so how do i use it? can it monitor ios simulator traffic?

**Comment by azurebld** [comment] 2017-06-05 15:48
ok, here's the log with iphone simulator, dont know if it's the right one

GET /mads/gma?os_version=10.3.0&u_sso=p&ios_base_sdk=10.3&rbv=1&platform=iPhone&request_id=12&app_name=20.iphone.com.blake.jigsaw&u_mwsso=p&u_so=p&js=afma-sdk-i-v7.20.0&sai=1&ios_app_volume=1&is_other_audio_playing=0&ios_output_volume=1&ios_current_boot_timestamp_ms=48719995.175&request_origin=pub&ms=11&hl=en&u_sd=3&ios_key_window_w=414&cap_noiap=0&u_w=414&format=interstitial_mb&u_h=736&submodel=x86_64&ios_key_window_h=736&cap_bs=1&net=wi&ios_app_muted=0&binary_arch=x86_64&adtest=on&_package_name=com.blake.jigsaw&u_audio=4&an=20.iphone.com.blake.jigsaw&output=html&region=mobile_app&u_tz=480&client_sdk=1&ex=1&client=ca-app-pub-3940256099942544&slotname=1712485313&_hl=en&gsb=wi&num_ads=1&vpt=8&vfmt=18&vst=0&sdkv=o.7.20.0&sdmax=0&dmax=1&sdki=3c0d&caps=interactiveVideo_inlineVideo_mraid1_mraid2_th_autoplay_mediation_av_sdkAdmobApiForAds_di_transparentBackground_sdkVideo_aso_sfv_dinm_dim_nav_ct_dinmo_gcache&swdr=false&blockAutoClicks=true&_efs=true&forceHttps=true&includeDoritos=true&eid=318477338&tcar=1&jsv=4-production-20170529_RC00&urll=1076 HTTP/1.1

Host: googleads.g.doubleclick.net
Accept: */*
Cookie: id=225a94a19a3e00f3||t=1496571865|et=730|cs=002213fd48c4e10f795fa96a17
User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E269
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive

and response:
{
	"ad_type": "interstitial",
	"qdata": "x",
	"ad_networks": [{
		"adapters": ["com.google.DummyAdapter"],
		"id": ""
	}],
	"settings": {
		"click_urls": ["@gw_adnetid@"],
		"imp_urls": [],
		"nofill_urls": ["https:\/\/pagead2.googleadservices.com\/pagead\/adview?ai=C_nF2pnw1WbaYEILw2AT2rpWQDfnJ2qYF0e-FupIBABAIIMLs3CBgndHUgbAFiAEBqQIAAAAAgIQuQagDAaoEGU_Q6akn9iIp3jH5FtHcIO20Q1M3ajjJM7WQBgHABguAB4H4qTCYBwHSCAUIgGEQAQ\u0026sigh=AT8GxmRW1vk\u0026cid=CAASBORoH5A\u0026gvr=1", "https:\/\/googleads.g.doubleclick.net\/pagead\/conversion\/?ai=C_nF2pnw1WbaYEILw2AT2rpWQDfnJ2qYF0e-FupIBABAIIMLs3CBgndHUgbAFiAEBqQIAAAAAgIQuQagDAaoEGU_Q6akn9iIp3jH5FtHcIO20Q1M3ajjJM7WQBgHABguAB4H4qTCYBwHSCAUIgGEQAQ\u0026sigh=ZAI0d9OFUS0\u0026label=admob_mediation_request_fill_result\u0026mediation_fill_status=@gw_adnetstatus@\u0026cid=CAASBORoH5A"],
		"rewards": [{
			"rb_type": "coins",
			"rb_amount": 10
		}]
	}
}

**Comment by azurebld** [comment] 2017-06-05 15:52
besides, xcode warning is: 

<Google> Cannot find an ad network adapter with the name(s): com.google.DummyAdapter. Remember to link all required ad network adapters and SDKs, and set -ObjC in the 'Other Linker Flags' setting of your build target.

-[GADRewardBasedVideoAdDelegate rewardBasedVideoAd:didFailToLoadWithError:]:
 video error: Error Domain=com.google.ads Code=9 "No ad returned from any ad server." UserInfo={NSLocalizedDescription=No ad returned from any ad server., NSLocalizedFailureReason=No ad returned from any ad server.}

**Comment by azurebld** [comment] 2017-06-05 16:15
uploaded a charles session file for convenience
https://github.com/cngamegirl/cngamegirl.github.io/blob/master/Untitled.chls.zip

**Comment by ericleich** [comment] 2017-06-05 22:43
Hi @azurebld 

Thanks for downloading and setting up Charles, and providing the Charles log! I have confirmed that with the exact same ad request url from your log, I'm able to get fill on my end. I'm pretty sure this has something to do with your location (looks like your request is coming from Beijing), as I have heard one other report of our rewarded video test ad not serving from China. This is an ad serving question that is outside my area of expertise, so I'll have to ask around to get more information on this. I do have what I need to escalate though.

**Comment by ericleich** [comment] 2017-06-08 16:03
I confirmed the problem. The test ad campaign we're running uses YouTube to host the video, and YouTube is [blocked](https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China) in China. So this ad isn't eligible to serve from your IP and therefore there is a no fill.

I don't have a solution for you at the moment, unfortunately. I haven't figured out a way yet to set up a non-YouTube test ad.

**Comment by oneLeaf2012** [comment] 2017-06-16 15:34
Incentive video in China?

**Comment by oneLeaf2012** [comment] 2017-06-16 15:37
Cannot display incentive video advertising in China?

**Comment by twitteriosdevelopment** [comment] 2017-06-18 01:44
I have the same problem but in New Zealand tho^^

**Comment by ericleich** [comment] 2017-06-19 15:45
I don't know what the state is for all rewarded advertising. I can only confirm that the test ad specifically is served via YouTube. Anecdotally, azurebid said up above that real ads were serving.

**Comment by ericleich** [comment] 2017-07-10 16:28
I'm closing this issue as it is not related to the sample apps on this repo. For addtional support, please use the [Google Mobile Ads SDK developer forum](//groups.google.com/group/google-admob-ads-sdk).

**Closed by ericleich** 2017-07-10 16:28 UTC
