### ISSUE TITLE
NativeExpressAds capture swipe events in UITableView (scrolling bug)

### ISSUE THREAD

**Issue by L4grange** [googleads/googleads-mobile-ios-examples#59] opened 2017-07-26 15:02 UTC
Hello. When NativeExpressAdViews are added as UITableViewCells, the adviews capture the swipe events, making the list impossible to swipe when the gesture begins from inside an Adview Cell. I can understand that the webview needs to capture taps, but why swipes too? This results in a poor user experience when using the nativeAds in a UITableView.

I am able to reproduce this bug in my own app as well as in the advanced UITableView with NativeExpressAds example in this repo. If you have any suggestions, let me know. Thank you!

P.S.: Tested on ios 10

**Comment by ericleich** [comment] 2017-07-27 15:35
So, the [UIWebView docs](https://developer.apple.com/documentation/uikit/uiwebview) explicitly say:

    You should not embed UIWebView or UITableView objects in UIScrollView objects.
    If you do so, unexpected behavior can result because touch events for the two objects
    can be mixed up and wrongly handled.

A lot of apps do it anyways, hence the sample exists due to popular demand.

In this case, it is the ad itself that may be consuming the swipe gesture. I couldn't reproduce this just now in the same example you mentioned, but I might have gotten different ads back. Most if not all of Google's ad formats don't consume swipe gestures. If a third party ad wins through the Ad Exchange however, all bets are off. And it's outside the scope of this issue, but if you're mediating, there's also a risk that ads from other ad networks block these swipes as well.

I'm going to close this issue since there's nothing the sample (or your app) can do to work around this.

**Closed by ericleich** 2017-07-27 15:35 UTC

**Comment by L4grange** [comment] 2017-07-28 09:05
Thanks for the reply. I was using the sample app with the sample ad unit and I can see a slight up and down scrolling in the ad's webview when it captures the event. Please see it yourself on the capture I made here: http://imgur.com/Z0yYTJM

Note that I was not using mediation, just the pure example that is up on this repo.

The question now is why we have NativeAds, advertised as "the way to put ads in lists" when they are not supposed to be used in that way? Thanks for your help!

**Comment by ericleich** [comment] 2017-07-28 20:31
Weird. I reproduced on iOS 6 emulator, but not a plus device. I'm guessing the slight difference has to do with partial pixels which results in scrolling being necessary on the ad, which in turn means the webview needs the scrool.

In [this line](https://github.com/googleads/googleads-mobile-ios-examples/blob/master/Objective-C/advanced/NativeExpressTableViewExample/NativeExpressTableViewExample/TableViewController.m#L85), try adding 1 to the row height for the banner. This fixed the issue for me on a non-plus device.

**Comment by L4grange** [comment] 2017-08-01 09:59
The +1 pixel works perfectly to be honest. Thank you for this, I'm gonna use it in my app, since it does not make a significant visual difference. The weird thing is that it is only needed on my Swift app and not on my objC version. If you ever have any updated on this situation let me know.

Thanks for your solution :)
