### ISSUE TITLE
The sample apps just plain don't work. 

### ISSUE THREAD

**Issue by pjcook** [googleads/googleads-mobile-ios-examples#83] opened 2018-12-07 09:02 UTC
Using the latest SDK 7.36.0 with Xcode 10 and a real device. All I did was download the AdManagerBannerExample sample, change the development team and ran it on a real device. It doesn't work. 

I did this after finally finding these sample apps after spending a whole day trying to follow the example code and getting the same non results.

If you look in the console log I'm about to post it does say that I have restrict ad tracking set on my device. Whether this is enabled or disabled makes no difference. This is also a "clean" device with no extra apps, software or ad blockers running.

`2018-12-07 09:05:44.434665+0000 AdManagerBannerExample[1922:883963] [DYMTLInitPlatform] platform initialization successful
Google Mobile Ads SDK version: afma-sdk-i-v7.36.0
2018-12-07 09:05:44.722173+0000 AdManagerBannerExample[1922:883919] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-12-07 09:05:44.722503+0000 AdManagerBannerExample[1922:883919] [MC] Reading from public effective user settings.
2018-12-07 09:05:44.726959+0000 AdManagerBannerExample[1922:883919] <Google> Limit Ad Tracking may be enabled. To get test ads on this device, disable Limit AdTracking.
2018-12-07 09:05:44.799193+0000 AdManagerBannerExample[1922:883919] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
2018-12-07 09:05:44.800183+0000 AdManagerBannerExample[1922:883955] [NetworkInfo] Signal strength query returned error: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied", descriptor: <CTServiceDescriptor 0x281f0e800, domain=1, instance=1>
2018-12-07 09:05:44.839951+0000 AdManagerBannerExample[1922:883970] Metal GPU Frame Capture Enabled
2018-12-07 09:05:44.842421+0000 AdManagerBannerExample[1922:883970] Metal API Validation Enabled
2018-12-07 09:05:45.253940+0000 AdManagerBannerExample[1922:883988] WF: === Starting WebFilter logging for process AdManagerBannerExample
2018-12-07 09:05:45.253997+0000 AdManagerBannerExample[1922:883988] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    noOverridingAllowed = 1;
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2018-12-07 09:05:45.254039+0000 AdManagerBannerExample[1922:883988] WF: _WebFilterIsActive returning: NO
2018-12-07 09:05:45.471829+0000 AdManagerBannerExample[1922:883919] [avas] AVAudioSessionPortImpl.mm:56:ValidateRequiredFields: Unknown selected data source for Port Speaker (type: Speaker)
`

**Comment by stowy** [comment] 2018-12-27 21:35
Closing since I'm unable to reproduce using our sample apps, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**Closed by stowy** 2018-12-27 21:35 UTC

**Comment by Ornolfr** [comment] 2019-09-09 05:55
@stowy I'm getting this line in the logs: 
`<Google> Limit Ad Tracking may be enabled. To get test ads on this device, disable Limit AdTracking.`
Googling the line gives a single search result that points to this page.
