### ISSUE TITLE
SwiftUIDemo - Banner Ad height

### ISSUE THREAD

**Issue by saldous** [googleads/googleads-mobile-ios-examples#306] opened 2023-01-05 15:58 UTC
In your demo code, for banner ads, the height of the view doesn't match the height of the banner. And if there is no internet connection, banner doesn't load, but view size stays the same. How to fix this please? (SwiftUI)

**Comment by famapohl** [comment] 2023-02-23 08:45
To elaborate on the issue a bit further, it appears that UIViewControllerRepresentable is taking up the entire height of the screen. In the following screenshot I have given the `BannerView()` a blue background to illustrate the case. Maybe someone has a solution to bring the height of the UIViewControllerRepresentable to the height of the `GADBannerView()`.

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-23 at 09 44 40](https://user-images.githubusercontent.com/73182139/220859341-b8e93217-d53f-4476-ae9d-6582a6714ae4.png)

**Comment by saldous** [comment] 2023-02-23 12:40
@famapohl yes, this is exactly the issue. I've contacted their Support and they don't seem to know the answer either. The most common use case for a banner ad is for it to be at the bottom of the screen, but I can't make it go to the bottom! Using this sample project and putting a spacer in, banner ad still at top..

```
VStack(spacing: 0){
        Spacer()

        BannerView()
            .navigationTitle(navigationTitle).background(.green)
    }.background(.red)
  }
```

**Comment by saldous** [comment] 2023-02-23 16:30
Adding:

`.fixedSize(horizontal: false, vertical: true)`

to the BannerView seems to help, but when banner loads anything below the bannerView will be covered up.

e.g. 

```
VStack(spacing: 0) {
                Spacer()
                
                Text("Top Text")
                
                BannerView().background(.blue)
                    .fixedSize(horizontal: false, vertical: true)
                
                Text("Bottom Text")
                
                
            }
            .background(.red)
            .navigationTitle(navigationTitle)
            .padding(.bottom, 32)
```

In the above example, 'Bottom Text' gets covered up when ad loads.

**Comment by famapohl** [comment] 2023-02-23 17:11
Yes, i've also tried that but while using a `Spacer()` the `BannerView()` gets pushed under the bottom of the screen. (Using iPhone 14 Pro Simulator) I see you also fixed that with `.padding(.bottom, 32)` but I think that value needs to vary for different screen sizes. So that's unfortunately also not ideal.

**Comment by saldous** [comment] 2023-02-23 18:33
> Yes, i've also tried that but while using a `Spacer()` the `BannerView()` gets pushed under the bottom of the screen. (Using iPhone 14 Pro Simulator) I see you also fixed that with `.padding(.bottom, 32)` but I think that value needs to vary for different screen sizes. So that's unfortunately also not ideal.

Yes, totally not workable. Google need to fix this.

**Comment by saldous** [comment] 2023-02-24 16:11
I think I've found a 'hack'.. Using NotificationCenter, when ad is received I send a notification with the height of the add. In the SwiftUI view, I set the BannerView bottom padding to equal the height of the banner.. It seems to work, but I honestly think this is a hack and not the right way to do it:

`import GoogleMobileAds
import SwiftUI

@available(iOS 15.0, *)
struct BannerContentView: View {
    let navigationTitle: String
    @State private var adHeight: CGFloat = .zero
    
    var body: some View {
        VStack {
            Spacer()
            
            BannerView()
                .background(.blue)
                .fixedSize(horizontal: false, vertical: true)
                .padding(.bottom, adHeight)
        }
        .background(.green)
        
        .onReceive(NotificationCenter.default.publisher(for: NSNotification.Name("BannerHeight")))
        { obj in
            if let height = obj.userInfo?["BannerHeight"] as? CGFloat {
                adHeight = height
            }
        }
        
        .navigationTitle(navigationTitle)
    }
}

private struct BannerView: UIViewControllerRepresentable {
    @State private var viewWidth: CGFloat = .zero
    private let bannerView = GADBannerView()
    private let adUnitID = "ca-app-pub-3940256099942544/2435281174"
    
    func makeUIViewController(context: Context) -> some UIViewController {
        let bannerViewController = BannerViewController()
        bannerView.adUnitID = adUnitID
        bannerView.rootViewController = bannerViewController
        bannerView.delegate = context.coordinator
        bannerViewController.view.addSubview(bannerView)
        bannerViewController.delegate = context.coordinator
        
        return bannerViewController
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
        guard viewWidth != .zero else { return }
        
        bannerView.adSize = GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(viewWidth)
        bannerView.load(GADRequest())
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }
    
    fileprivate class Coordinator: NSObject, BannerViewControllerWidthDelegate, GADBannerViewDelegate
    {
        let parent: BannerView
        
        init(_ parent: BannerView) {
            self.parent = parent
        }
        
        // MARK: - BannerViewControllerWidthDelegate methods
        
        func bannerViewController(
            _ bannerViewController: BannerViewController, didUpdate width: CGFloat
        ) {
            parent.viewWidth = width
        }
        
        // MARK: - GADBannerViewDelegate methods
        
        func bannerViewDidReceiveAd(_ bannerView: GADBannerView) {
            print("DID RECEIVE AD")
            
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "BannerHeight"), object: nil, userInfo: ["BannerHeight" : bannerView.adSize.size.height])
        }
        
        func bannerView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: Error) {
            print("DID NOT RECEIVE AD: \(error.localizedDescription)")
        }
    }
}

protocol BannerViewControllerWidthDelegate: AnyObject {
    func bannerViewController(_ bannerViewController: BannerViewController, didUpdate width: CGFloat)
}

class BannerViewController: UIViewController {
    
    weak var delegate: BannerViewControllerWidthDelegate?
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        delegate?.bannerViewController(
            self, didUpdate: view.frame.inset(by: view.safeAreaInsets).size.width)
    }
    
    override func viewWillTransition(
        to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator
    ) {
        coordinator.animate { _ in
            // do nothing
        } completion: { _ in
            self.delegate?.bannerViewController(
                self, didUpdate: self.view.frame.inset(by: self.view.safeAreaInsets).size.width)
        }
    }
}
`

**Comment by famapohl** [comment] 2023-02-28 19:46
@saldous thanks for your support. I will definitely try this out. Nevertheless, I also hope this will be fixed the right way soon.

**Comment by jadelizardsoftware** [comment] 2023-03-01 03:29
The issue is the UIViewController is not being resized. The solution I came up with was to set the UIViewController's preferredContentSize based on the ad's frame. When there is no ad to display, the preferredContentSize is empty. Once the ad loads it sets the preferredContentSize to the ad's size. This is done by overriding viewDidLayoutSubviews. See the example below.

Simply add the following:

```
class BannerViewController: UIViewController {
    
    weak var delegate: BannerViewControllerWidthDelegate?
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        delegate?.bannerViewController(self, didUpdate: view.frame.inset(by: view.safeAreaInsets).size.width)
    }
    
    // --------- ADDED THIS --------
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let width = view.frame.inset(by: view.safeAreaInsets).size.width
        let targetSize = CGSize(
            width: width,
            height: GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(width).size.height
        )
        
        // Set preferred content size so banner only take up space if needed
        self.preferredContentSize = self.view.systemLayoutSizeFitting(targetSize)
    }
    
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate { _ in } completion: { _ in
            self.delegate?.bannerViewController(
                self, didUpdate: self.view.frame.inset(by: self.view.safeAreaInsets).size.width
            )
        }
    }
}
```

**Comment by saldous** [comment] 2023-03-01 12:52
@jadelizardsoftware thanks! It looks like I still have to use .fixedSize(horizontal: false, vertical: true) on the view for this to work.

```
VStack {
            VStack {
                Text("Text on top")
                Spacer()
                
                Text("Text above banner")
                BannerView()
                    .background(.blue)
                    .fixedSize(horizontal: false, vertical: true)
                Text("Text below banner")
            }
            

        }
        .navigationTitle(navigationTitle)
```

**Comment by jadelizardsoftware** [comment] 2023-03-01 18:39
@saldous, no problem I'm glad it's working for you. I also found that the banner demo doesn't handle screen size changes well. Specifically, if I remember correctly, when an iPad split screen app size changes (e.g. from 2/3 to 1/3), the banner doesn't reload and display at the correct size. If anyone else runs into this issue I'd be happy to share my solution.

**Comment by saldous** [comment] 2023-03-01 18:40
@jadelizardsoftware yes please share that solution too! I have just been testing and running into the same. Thanks.

**Comment by famapohl** [comment] 2023-03-01 20:18
@saldous @jadelizardsoftware thank you guys, the banner works like a charm now.

**Comment by malandr2** [comment] 2023-03-01 21:44
Thank you all for providing these code snippets. One thing is we strongly recommend against using the `NotificationContentCenter` as a means to fetch the height. 

For our sample, this is simply a singular `GADBannerView` positioned in its super view (`viewcontroller.view`). `UIViewControllerRepresentable` has a layout priority to take up the available space, so there is a difference in height by design. 

While the code snippet provided in the comments changes the layout behavior for `UIViewControllerRepresentable`, it is completely valid as there are scenarios when you would want to do so. For our sample, we do not need to change the layout behavior. 

For others coming here with a similar question, please refer to the above code snippets for your use case. That looks good to me. I'll be closing this issue. Thanks all for the discussion.

**Closed by malandr2** 2023-03-01 21:44 UTC

**Comment by famapohl** [comment] 2023-03-05 20:30
> @saldous, no problem I'm glad it's working for you. I also found that the banner demo doesn't handle screen size changes well. Specifically, if I remember correctly, when an iPad split screen app size changes (e.g. from 2/3 to 1/3), the banner doesn't reload and display at the correct size. If anyone else runs into this issue I'd be happy to share my solution.

@jadelizardsoftware would you still share the solution to this problem? I would appreciate it very much!

**Comment by saldous** [comment] 2023-12-10 21:09
@malandr2 the problem with this is that if no banner loads (e.g. no internet connection) the space for the banner remains on the screen leaving a big gap in the UI. How to fix this?

// --------- ADDED THIS --------
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        let width = view.frame.inset(by: view.safeAreaInsets).size.width
        let targetSize = CGSize(
            width: width,
            height: GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(width).size.height
        )
        
        // Set preferred content size so banner only take up space if needed
        self.preferredContentSize = self.view.systemLayoutSizeFitting(targetSize)
    }

**Comment by saldous** [comment] 2023-12-11 18:30
@marlandr2 & @jadelizardsoftware this appears to work, is this a valid solution?

```
import SwiftUI
import GoogleMobileAds

struct AdMobTesting: View {
    @State private var adLoaded = false
    
    var body: some View {
        VStack(spacing: 0) {
            Text("Top Text")
            
            Spacer()
            
            Text("Middle Text")
            
            Spacer()
            
            Text("Bottom Text")
            
            BannerView(adLoaded: $adLoaded)
                .frame(height: adLoaded ? 50 : 0)
        }
    }
}


protocol BannerViewControllerDelegate: AnyObject {
    func bannerViewController(_ bannerViewController: BannerViewController, didUpdate width: CGFloat)
}

class BannerViewController: UIViewController {
    weak var delegate: BannerViewControllerDelegate?
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        delegate?.bannerViewController(self, didUpdate: view.frame.inset(by: view.safeAreaInsets).size.width)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        let width = view.frame.inset(by: view.safeAreaInsets).size.width
        
        let targetSize = CGSize(
            width: width,
            height: GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth(width).size.height
        )
        
        // Set preferred content size so banner only take up space if needed
        self.preferredContentSize = self.view.systemLayoutSizeFitting(targetSize)
    }
    
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        coordinator.animate { _ in } completion: { _ in
            self.delegate?.bannerViewController(
                self, didUpdate: self.view.frame.inset(by: self.view.safeAreaInsets).size.width
            )
        }
    }
}

private struct BannerView: UIViewControllerRepresentable {
    @Binding var adLoaded: Bool
    @State private var viewWidth: CGFloat = .zero
    
    private let bannerView = GADBannerView()
    private let adUnitID = "ca-app-pub-3940256099942544/2934735716" // Test AdID
    
    func makeUIViewController(context: Context) -> some UIViewController {
        let bannerViewController = BannerViewController()
        bannerView.adUnitID = adUnitID
        bannerView.rootViewController = bannerViewController
        bannerView.delegate = context.coordinator
        bannerView.translatesAutoresizingMaskIntoConstraints = false
        bannerViewController.view.addSubview(bannerView)
        
        // Position the GADBannerView at the bottom of the view
        NSLayoutConstraint.activate([
            bannerView.bottomAnchor.constraint(equalTo: bannerViewController.view.safeAreaLayoutGuide.bottomAnchor),
            bannerView.centerXAnchor.constraint(equalTo: bannerViewController.view.centerXAnchor)
        ])
        
        bannerViewController.delegate = context.coordinator
        
        return bannerViewController
    }
    
    func updateUIViewController(_ uiViewController: UIViewControllerType, context: Context) {
        // Load the ad regardless of the current adLoaded state
        guard viewWidth != .zero else { return }

        bannerView.adSize = GADAdSizeBanner
        bannerView.load(GADRequest())

        // Adjust the size of the ad view based on whether an ad is loaded
        uiViewController.preferredContentSize = adLoaded ? CGSize(width: viewWidth, height: 50) : .zero
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(parent: self)
    }
    
    fileprivate class Coordinator: NSObject, BannerViewControllerDelegate, GADBannerViewDelegate {
        func bannerViewController(_ bannerViewController: BannerViewController, didUpdate width: CGFloat) {
            parent.viewWidth = width
        }
        
        let parent: BannerView
        
        init(parent: BannerView) {
            self.parent = parent
        }
        
        func bannerViewDidReceiveAd(_ bannerView: GADBannerView) {
            print("Ad Loaded")
            
            parent.bannerView.alpha = 1
            parent.adLoaded = true
        }
        
        func bannerView(_ bannerView: GADBannerView, didFailToReceiveAdWithError error: Error) {
            print("Ad Failed to load. Error: \(error.localizedDescription)")
            
            parent.bannerView.alpha = 0
            parent.adLoaded = false
        }
    }
}

```
