### ISSUE TITLE
Interstitial cannot be closed in 7.37.0

### ISSUE THREAD

**Issue by kiruto** [googleads/googleads-mobile-ios-examples#84] opened 2018-12-25 01:03 UTC
Since I upgraded sdk to 7.37.0, click event on both "close" button and "info" which cannot been response on interstitial.

**Comment by stowy** [comment] 2018-12-26 04:03
Hi, thanks for reporting your issue.

A few questions - are you seeing this in our 'InterstitialExample' app? Are you referring to test ads or real ads, on device or simulator? Which version of iOS and what type of device are you testing with?

Testing on simulator I am not able to reproduce this issue with test ads in the sample app.

Please confirm the repro environment for me to advise further.

Thanks

Sam

**Comment by kiruto** [comment] 2018-12-27 02:10
Thanks for your reply.

- are you seeing this in our 'InterstitialExample' app?
No, I haven't compile example codes myself. It happened in my APP.

- Are you referring to test ads or real ads, on device or simulator?
Both of them.

- Which version of iOS and what type of device are you testing with?
All devices.

I'll try to compile the example codes myself.
There may some issues with my code, but I really not doing any thing with Status Bars, or fullscreen.

**Comment by stowy** [comment] 2018-12-27 21:34
No problems, if there is not an issue with a sample app, more in depth support for your specific issue is handled by our support team on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

Closing this in light of above.

**Closed by stowy** 2018-12-27 21:34 UTC

**Comment by ithotdog** [comment] 2019-08-29 03:27
Hello, how to solve this problem?
