### ISSUE TITLE
two rewardVideo problems

### ISSUE THREAD

**Issue by azurebld** [googleads/googleads-mobile-ios-examples#52] opened 2017-06-27 06:48 UTC
hello!

we encountered 2 problems while testing admob reward ads.

1. sometimes a non-reward-video-ad is served
https://github.com/cngamegirl/cngamegirl.github.io/blob/master/admobbug.chls.zip

2. we always preload ads and check availability before presenting it, but sometimes the video just  pause/freeze. i suspect the ads is not fully cached when it's ready to show?????
we encounter this problem on interstitial video ads too, the count-down number stops counting and then disappear when time is up

**Comment by ericleich** [comment] 2017-06-27 19:16
For 1), that request in the charles log is for a 400x333 ad against a Native express ad unit. Did you send over the right charles log?

For 2), the onAdLoaded callback currently does happen before the full video is fully loaded, but it's generally expected that the video will finish loading before it ever needs to buffer. How often is this happening? I'd expect this to be a corner case that only shows up when you have a spotty connection.

**Comment by azurebld** [comment] 2017-06-28 04:17
hmmm,ok,this time i disabled other ad types.
https://github.com/cngamegirl/cngamegirl.github.io/blob/master/admobbug2.chls.zip
https://github.com/cngamegirl/cngamegirl.github.io/blob/master/admobbug2.png
the ads seem to be containing same contents. first two times ad is ok. the third time only the above image showed up. the same happened when i test on device before, only a image like this that you can scroll left and right. no video, no reward callback.

for 2), i am not sure how bad our office network is and how often this will happen..... but we think it's a great frustration for our app users if it ever happens, we havent put admob reward ads in production environment as of now

**Comment by 2819936788** [comment] 2017-06-28 05:22
hellow i am  only test rewardBasedVideoAd  that  error   
Error Domain=com.google.ads Code=1 "Request Error: No ad to show." UserInfo={NSLocalizedDescription=Request Error: No ad to show., NSLocalizedFailureReason=Request Error: No ad to show.}

**Comment by ericleich** [comment] 2017-06-30 00:31
@azurebld 

From the Charles log, I do see rewarded requests now. The ad that's returning does seem to be a video ad. I'm not sure why it wouldn't play the video, but it does sound like a bug. I will have to circle back and follow up with you.

For 2), I'll share the feedback that you want some callback to know when the video has fully loaded.

**Comment by ericleich** [comment] 2017-06-30 20:47
For 1), there is a bug in the SDK. If the video doesn't load, we do show just the end card. This is fine for an interstitial placement but not for rewarded. This will be fixed, but I don't have an ETA to share.

For 2), it isn't just a simple answer to prefetch the entire video. It's a balance between prefetching enough and not wasting network usage for an ad that may not be shown. Plus, ExoPlayer has a [buffer policy](https://github.com/google/ExoPlayer/issues/2083) of 30s, so it's currently not feasible to fully cache long videos. That said, the team is investigating how to better optimize precaching.

I'm going to close this issue since I've confirmed it's not a problem with the samples themselves. If you have additional questions regarding this, please ask on the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk).

**Closed by ericleich** 2017-06-30 20:47 UTC
