### ISSUE TITLE
Can't close admob interstitial 

### ISSUE THREAD

**Issue by ithotdog** [googleads/googleads-mobile-ios-examples#120] opened 2019-08-29 02:56 UTC
Can't close admob interstitial  

Clicking the close button in the top left corner does not respond

Please reply, it’s urgent. 

![image](https://user-images.githubusercontent.com/22271843/63906697-740edd80-ca4b-11e9-9d8e-76ff580d7cb2.png)

**Comment by ithotdog** [comment] 2019-08-29 03:06
Only the UI ads provided by Google cannot be closed normally, others are possible.

**Comment by ithotdog** [comment] 2019-08-29 03:25
Click on other areas to jump to the browser.

**Comment by Sky0372Lsk** [comment] 2019-09-12 06:38
do you solve

**Comment by ithotdog** [comment] 2019-09-17 01:32
Yes, I have solved it.
I found that I responded to the touchBegin method when I clicked the close button.
So I dismiss the controller in the touchBegin method.

**Comment by usman-whizpool** [comment] 2020-07-22 05:03
![image_2020_07_22T04_55_37_563Z](https://user-images.githubusercontent.com/5094671/88136383-8add9600-cc02-11ea-9e4e-9cd4c58d424b.png)

we are getting too many bad reviews due to ads.. specially some lending tree ad

**Comment by usman-whizpool** [comment] 2020-07-28 04:22
![image0](https://user-images.githubusercontent.com/5094671/88618960-d89b4800-d0b3-11ea-9b35-098cf06fcbf6.png)

**Comment by leventepal** [comment] 2020-09-10 19:42
I'm having the same problem. I'm getting negative user ratings because my users are stuck with the internstitial ads. As posted above, the "X" or "CLOSE" buttons are not visibile and the back button is also disabled. This must be fixed ASAP!

**Comment by cuongtv51** [comment] 2020-11-18 04:09
Same Problem, :(

**Comment by stowy** [comment] 2020-11-18 04:35
Sorry we have limited capacity for support on this channel, please report the issue to [our developer forum](https://groups.google.com/g/google-admob-ads-sdk), this is not a Unity specific problem, it is related to the underlying SDK.  When reporting please provide as much information to reproduce as possible including the [response ID](https://developers.google.com/admob/unity/response-info) for the ad in question and / or a charles log.

**Comment by smin99** [comment] 2021-05-04 17:42
I'm having similar problem where close buttons are behind the status bar. Is there any solution came out?

![Uploading IMG_0196.PNG…]()

**Comment by uzumaki258** [comment] 2021-09-12 01:37
Very annoying for users. I have to block 500 app install, but now I see even web ads still same issue.

**Comment by malandr2** [comment] 2023-10-16 23:47
Closing this issue as it is not a direct problem related to our code samples. If you are still seeing this issue. Please go to our [Developers Forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk).

**Closed by malandr2** 2023-10-16 23:47 UTC
