### ISSUE TITLE
incorrect banner size on iOS 11

### ISSUE THREAD

**Issue by threat70** [googleads/googleads-mobile-ios-examples#49] opened 2017-06-08 06:50 UTC
hi all.
In beta iOS 11.0 the banner does not look right, It is moved below the bottom edge

![img_1301](https://user-images.githubusercontent.com/10289829/26915644-1f6d556a-4c51-11e7-93a9-9ebae658a205.png)

**Comment by ericleich** [comment] 2017-06-08 15:41
Thanks for reporting. This is probably an SDK issue rather than a serving issue, but I'll leave this open until we verify.

That said, are you mediating? That AdChoices icon looks different than what AdMob would serve.

**Comment by threat70** [comment] 2017-06-08 16:31
I have integrated only facebook audience network, this also occur with admob

**Comment by ericleich** [comment] 2017-06-08 16:35
Got it, it's still very possible AdMob mediation is laying this out incorrectly on iOS 11.

**Comment by threat70** [comment] 2017-06-08 16:37
I also noticed that in other my app is all ok. But difference in many things:
- release\debug mode
- Xcode8\Xcode9

I'll try to find the cause of the problem

**Comment by ericleich** [comment] 2017-06-08 16:51
If I were you I wouldn't spend too much time debugging it right now.

iOS 11 beta just came out this week. The latest AdMob SDK was released before that, so clearly it hasn't been tested against iOS 11/Xcode 9. We expect to find other bugs due to changes in the OS between now and September (when iOS typically moves out of a beta). All known issues will get fixed before iOS 11 gets released to user devices. Between now and then, I can't guarantee exactly when this particular issue will get investigated.

**Comment by ericleich** [comment] 2017-08-16 15:30
@threat70 throughout our testing, we haven't come across this problem. I also couldn't reproduce with the BannerExample project in this repo. Is this is still happening for you? If so, can you provide repro steps?

**Comment by ericleich** [comment] 2017-09-13 18:23
Just an update here, we finally found a repro case, and this will be fixed for the next SDK release (version 7.24.0) which will come out soon. Closing this issue as it's not related to the sample apps themselves.

**Closed by ericleich** 2017-09-13 18:23 UTC
