### ISSUE TITLE
Interstitial Ads - Problem with iPhone 14 Pro "Dynamic Island"

### ISSUE THREAD

**Issue by RobertEmoji** [googleads/googleads-mobile-ios-examples#292] opened 2022-09-22 17:35 UTC
The full screen interstitial ads have a bad appearance on the new iPhone 14 Pro screen.

Parts of the ad are hidden behind the "dynamic island".
And the close button (x) of an interstitial ad is hard to hit, because it's outside of the safe area of the screen.

**Comment by BastienPenalba** [comment] 2022-09-27 12:51
Same issue here 😬

Also seen in the flutter and [SPM version](https://github.com/googleads/swift-package-manager-google-mobile-ads/issues/15)

Users get stuck watching an ad without the possibility to navigate the app which is terrible for user retention. I guess that could be fixed directly in the ads webview and will not necessarily trigger a new version. So it would be cool to have any feedback here if this gets fixed "remotely" please 🙏

**Comment by januks** [comment] 2022-09-28 11:43
Found the same problem when compiling new application versions and tested some adds. Time to time happens, that some adds are behind dynamic island and can't be closed.
Can't release application before it's resolved.

**Comment by PrakashMaharjan** [comment] 2022-09-29 09:25
same issue.. cannot close the rewarded ad full screen as the cross button is below dynamic island. any update?

**Comment by steverobert** [comment] 2022-09-30 03:52
Same here....

**Comment by Hmeedo** [comment] 2022-10-07 10:40
same here...

**Comment by mikehardy** [comment] 2022-10-08 14:38
Support team is aware, follow the mailing list, or perhaps the example here will be updated: https://groups.google.com/g/google-admob-ads-sdk/c/JqS14ZpvTGw/m/xtLOEXwJAgAJ

> Thank you for raising this to us. The reported behavior has been flagged to a wider team for investigation. We'll update this thread the soonest the team share their feedback.

**Comment by youcaihuaF** [comment] 2022-10-10 09:53
same here...

**Comment by mikehardy** [comment] 2022-10-10 18:34
@youcaihuaF "me too" comments are spam. Do you have anything to ad to move the issue forward or ?

**Comment by LiveXenon** [comment] 2022-11-03 21:37
I attach the logs extracted from Xcode when an interstitial ad is opened:

> Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.

What I noticed is that the log appears both if the device is an iPhone 14 Pro iOS 16 (in this case the advertisement cannot be closed) and with lower models (for example iPhone 13 iOS 16) but in this case the close button is reachable and working .

<img width="459" alt="Schermata 2022-10-05 alle 14 26 32" src="https://user-images.githubusercontent.com/34724827/199838513-5554c402-56ba-4a5f-bdfd-77324ab8342a.png">
<img width="446" alt="Screenshot 2022-11-03 alle 22 35 57" src="https://user-images.githubusercontent.com/34724827/199839049-f0cb8c17-c7cf-44a8-b252-caca295cd2c1.png">

**Comment by mikehardy** [comment] 2022-11-04 15:06
That last comment is putting more effort in, thank you, but boils down to the exact first post:

> The full screen interstitial ads have a bad appearance on the new iPhone 14 Pro screen.
> 
> Parts of the ad are hidden behind the "dynamic island".
> And the close button (x) of an interstitial ad is hard to hit, because it's outside of the safe area of the screen.

Thus does not move the issue forward.

What are others doing based on your research in the upstream support mailing list?
What code changes are necessary here in order to correctly handle dynamic island in full screen ads?
Is this important enough for an affected company to propose a PR to implement the necessary changes in a PR and post it here?

These are the steps to follow to resolve this

**Comment by halilyilmaz** [comment] 2022-12-02 06:41
Hi, 
I have same issue in my applications. I found one solution. It's not perfect but it works. 
You can hide status bar before show the ad and after when ad dismissed you can show status bar again. I can close ads like this.

if UIDevice.current.checkIfHasDynamicIsland() {
    UIApplication.shared.isStatusBarHidden = true
}

**Comment by mikehardy** [comment] 2022-12-02 12:28
@halilyilmaz that actually seems pretty reasonable as a workaround. It is a pretty major issue to have a non-close-able ad, and temporarily not showing the status bar is not *that* bad on a scale of "maybe bad behavior". If you made a PR for that to the code showing full screen ads and it looked good, I think that is merge-able

**Comment by LiveXenon** [comment] 2022-12-02 13:09
It seems that compiling the app with **Xcode Version 14.1 (14B47b)** and **iOS 16.1** solves the problem, I can't give an explanation but this is the result:

![Screenshot 2022-11-12 alle 18 40 33](https://user-images.githubusercontent.com/34724827/205298656-9891258a-cff7-4626-9431-25dfa10b7df2.png)

My app uses React Native, the only modules I've updated are:

```
 "react-native": "0.66.3" ->  "0.66.5"
 "react-native-screens": "^3.9.0" -> "^3.14.0"
```

I hope this can help someone.

**Comment by JillSong** [comment] 2023-11-10 17:13
Thanks for everyone contributing to this thread. The issue is not related to this repo and or the SDK itself. It's a creative issue which has been tracked internally. Closing the thread.

**Closed by JillSong** 2023-11-10 17:13 UTC

**Comment by chuckboris** [comment] 2023-11-16 15:16
I have found that the error
 > Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.

and therefore the unreachable button, can be caused by "View controller-based status bar appearance" set to NO in the Info.plist file. I could not find this information in the documentation or anywhere else.

**Comment by mikehardy** [comment] 2023-11-18 03:09
@chuckboris fasinating!! If there is some place in our docs that looks like a good place to put it, every page has an edit button at the top right if I recall correctly...

**Comment by AmirCa84** [comment] 2024-04-04 19:18
> I have found that the error
> 
> > Status bar could not be hidden for full screen ad. Ensure that your app is configured to allow full screen ads to control the status bar. For example, consider whether you need to set the childViewControllerForStatusBarHidden property on your ad's rootViewController.
> 
> and therefore the unreachable button, can be caused by "View controller-based status bar appearance" set to NO in the Info.plist file. I could not find this information in the documentation or anywhere else.

Thank you! It happens in the Xcode old project. It worked for me!
