### ISSUE TITLE
iOS device repeating message in log: "ProcessThrottler::Activity::invalidate: Ending foreground activity..."

### ISSUE THREAD

**Issue by wooyukit** [googleads/googleads-mobile-ios-examples#256] opened 2021-10-25 10:11 UTC
```
ProcessThrottler::Activity::invalidate: Ending foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ProcessThrottler::Activity::Activity: Starting foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ProcessThrottler::Activity::invalidate: Ending foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ProcessThrottler::Activity::Activity: Starting foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ProcessThrottler::Activity::Activity: Starting foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ProcessThrottler::Activity::invalidate: Ending foreground activity / 'WebPageProxy::runJavaScriptInFrameInScriptWorld'
    ....
```

The Google-Mobile-Ads-SDK updated to latest version 8.12.0. If I disable GADAdLoader and GADBannerView, the repeating log will be disappeared.

**Comment by JillSong** [comment] 2023-11-13 13:37
Cannot reproduce this issue anymore. Closing the thread.

**Closed by JillSong** 2023-11-13 13:37 UTC
